import assert from 'node:assert/strict';
import fs from 'node:fs/promises';
import { createHash } from 'node:crypto';
const source = await fs.readFile(new URL('../_worker.js', import.meta.url), 'utf8');
const worker = (await import('data:text/javascript;base64,' + Buffer.from(source).toString('base64'))).default;
const release = JSON.parse(await fs.readFile(new URL('../downloads/mile-camera-update.json', import.meta.url), 'utf8'));
const calls = [];
const env = { ASSETS: { async fetch(request) {
  const path = new URL(request.url).pathname; calls.push(path);
  if (path === '/downloads/mile-camera-update.json') return new Response(JSON.stringify(release), { headers: { 'content-type': 'application/json' } });
  return new Response(new Uint8Array([0x50,0x4b,3,4]), { headers: { 'content-type': 'application/octet-stream' } });
} } };
const response = await worker.fetch(new Request('https://mile.posnew.com/api/android/update'), env);
assert.equal(response.status, 200, 'Update checking works before login.');
assert.equal((await response.json()).versionCode, 8);
assert.equal(response.headers.get('cache-control'), 'no-store, max-age=0');
assert.equal(response.headers.get('cloudflare-cdn-cache-control'), 'no-store');
assert.equal(calls[0], '/downloads/mile-camera-update.json');
assert.equal(release.applicationId, 'com.posnew.milecamera');
assert.equal(release.versionName, '0.1.7');
assert.equal(release.downloadUrl, 'https://mile.posnew.com/downloads/Mile-Camera-0.1.7.apk');
const gradle = await fs.readFile(new URL('../android/app/build.gradle', import.meta.url), 'utf8');
assert.match(gradle, /versionCode 8/); assert.match(gradle, /versionName '0\.1\.7'/);
const denied = await worker.fetch(new Request('https://mile.posnew.com/api/android/update', { method: 'POST' }), env);
assert.equal(denied.status, 405); assert.equal(denied.headers.get('allow'), 'GET, HEAD');
const apk = await worker.fetch(new Request(release.downloadUrl), env);
assert.equal(apk.status, 200); assert.equal(apk.headers.get('content-type'), 'application/vnd.android.package-archive');
assert.equal(apk.headers.get('content-disposition'), 'attachment; filename="Mile-Camera-0.1.7.apk"');
const metadata = await worker.fetch(new Request('https://mile.posnew.com/downloads/mile-camera-update.json'), env);
assert.equal(metadata.status, 200, 'Release manifest is public.');
const built = await fs.readFile(new URL('../downloads/Mile-Camera-0.1.7.apk', import.meta.url));
assert.equal(createHash('sha256').update(built).digest('hex'), release.sha256, 'Public metadata identifies the APK actually shipped.');
assert.equal(built.length, release.bytes);
console.log('PASS Android update endpoint: public no-cache metadata, official APK, consistent version/build/hash, login not required, write methods rejected');
